format = """\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $time\
    $docker_context\
    $package\
    $golang\
    $java\
    $nodejs\
    $python\
    $rust\
    $conda\
    $aws\
    $memory_usage\
    $line_break\
    $character\
"""

scan_timeout = 10

[time]
format = "%Y-%m-%d %H:%M:%S"

[cmd_duration]
min_time = 500
prefix = "took "
enabled = false

[directory]
style = "bright-white"

[username]
disabled = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
vicmd_symbol = "[➜](bold green)"

[git_status]
style = "bright-red"
ahead = "  "
behind = "  "
diverged = "  "
untracked = "  "
stashed = "  "
modified = "  "
staged = "  "
renamed = "  "
deleted = "  "

[aws]
disabled = true
